openapi: 3.0.0
info:
  title: Common components
  version: 1.0.0
paths: {}

# Put your common components here:
components:
  securitySchemes:
    tui_auth:
      type: oauth2
        flows:
    #        implicit:
    #          authorizationUrl: https://tui-nonprod-group-test.apigee.net/pos
    #          scopes:
    #            admin: admin scope
    #            user: user scope
          authorizationCode:
            authorizationUrl: https://tui-nonprod-group-test.apigee.net/pos
            tokenUrl: https://tui-nonprod-group-test.apigee.net/oauth/client_credential/accesstoken
            refreshUrl: https://tui-nonprod-group-test.apigee.net/oauth/client_credential/refresh_accesstoken
            scopes:            
              admin: admin scope
              user: user scope